name: Test Environments

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  install:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: npm install
        run: npm ci
