name: Update docs for release
on:
  push:
    branches:
      - test
jobs:
  prepare-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          check-latest: true
          registry-url: 'registry.npmjs.org/'
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: ls
      - run: echo ${RUNNER_TEMP}
      - run: ls ${RUNNER_TEMP}
      - run: cat ${RUNNER_TEMP}/.npmrc
      # - name: Install dependencies
      #   run: npm ci
      # - name: Prepare dist
      #   run: npm run docs
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 'Update storybook for ${GITHUB_REF##*/}'
