on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release-please
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_KEY }}
          release-type: node
          package-name: release-please-action
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Testing
        run: echo "Stub here ${{ steps.extract_branch.outputs.branch }}"
      - name: Testing
        run: echo "Stub here ${{ steps.release-please.outputs.pr }}"
      - uses: actions/github-script@v5
        if: ${{ steps.release-please.outputs.pr }}
        id: find-branch
        env:
          PR_NUM: ${{ steps.release-please.outputs.pr }}
        with:
          result-encoding: string
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: process.env.PR_NUM,
            });
            return pullRequest.head.ref
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.find-branch.outputs.result }}
      - run: npm run docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update storybook for ${GITHUB_REF##*/}'
      

# - uses: actions/checkout@v2
#         if: ${{ steps.tag-release.outputs.release_created }}