on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release-please
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_KEY }}
          release-type: node
          package-name: release-please-action
      - name: Testing
        run: echo "Stub here ${{ steps.release-please.outputs.pr}} PR stuff  ${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}"
      # - uses: actions/checkout@v2
      #   with:
      #     stub: ${{ steps.release-please.outputs.major }}
